server:
  port: 8001


spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/db_demo?Unicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&serverTimezone=PRC
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: 123456
    filters:  stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    initialSize:  2
    minIdle: 1
    maxActive: 4
    maxWait: 60000


registry:
  address: 127.0.0.1:2181

rpc:
  server:
    host: 127.0.0.1
    port: 7001

